var WM_MESSAGE;
(function (WM_MESSAGE) {
    /**
     * 用户自定义消息起始值
     * @constant
    */
    WM_MESSAGE.WM_USER = 1024;
})(WM_MESSAGE || (WM_MESSAGE = {}));
;
/**
 * CEN/XFS 消息类型
 * @enum
*/
var WFSMESSAGE;
(function (WFSMESSAGE) {
    WFSMESSAGE[WFSMESSAGE["WFS_OPEN_COMPLETE"] = WM_MESSAGE.WM_USER + 1] = "WFS_OPEN_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_CLOSE_COMPLETE"] = WM_MESSAGE.WM_USER + 2] = "WFS_CLOSE_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_LOCK_COMPLETE"] = WM_MESSAGE.WM_USER + 3] = "WFS_LOCK_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_UNLOCK_COMPLETE"] = WM_MESSAGE.WM_USER + 4] = "WFS_UNLOCK_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_REGISTER_COMPLETE"] = WM_MESSAGE.WM_USER + 5] = "WFS_REGISTER_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_DEREGISTER_COMPLETE"] = WM_MESSAGE.WM_USER + 6] = "WFS_DEREGISTER_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_GETINFO_COMPLETE"] = WM_MESSAGE.WM_USER + 7] = "WFS_GETINFO_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_EXECUTE_COMPLETE"] = WM_MESSAGE.WM_USER + 8] = "WFS_EXECUTE_COMPLETE";
    WFSMESSAGE[WFSMESSAGE["WFS_EXECUTE_EVENT"] = WM_MESSAGE.WM_USER + 20] = "WFS_EXECUTE_EVENT";
    WFSMESSAGE[WFSMESSAGE["WFS_SERVICE_EVENT"] = WM_MESSAGE.WM_USER + 21] = "WFS_SERVICE_EVENT";
    WFSMESSAGE[WFSMESSAGE["WFS_USER_EVENT"] = WM_MESSAGE.WM_USER + 22] = "WFS_USER_EVENT";
    WFSMESSAGE[WFSMESSAGE["WFS_SYSTEM_EVENT"] = WM_MESSAGE.WM_USER + 23] = "WFS_SYSTEM_EVENT";
    WFSMESSAGE[WFSMESSAGE["WFS_TIMER_EVENT"] = WM_MESSAGE.WM_USER + 100] = "WFS_TIMER_EVENT";
})(WFSMESSAGE || (WFSMESSAGE = {}));
