namespace WM_MESSAGE {
/**
 * 用户自定义消息起始值
 * @constant
*/
export const WM_USER:number = 1024;

};

/**
 * CEN/XFS 消息类型
 * @enum
*/
enum WFSMESSAGE {
    WFS_OPEN_COMPLETE       = WM_MESSAGE.WM_USER + 1,
    WFS_CLOSE_COMPLETE      = WM_MESSAGE.WM_USER + 2,
    WFS_LOCK_COMPLETE       = WM_MESSAGE.WM_USER + 3,
    WFS_UNLOCK_COMPLETE     = WM_MESSAGE.WM_USER + 4,
    WFS_REGISTER_COMPLETE   = WM_MESSAGE.WM_USER + 5,
    WFS_DEREGISTER_COMPLETE = WM_MESSAGE.WM_USER + 6,
    WFS_GETINFO_COMPLETE    = WM_MESSAGE.WM_USER + 7,
    WFS_EXECUTE_COMPLETE    = WM_MESSAGE.WM_USER + 8,

    WFS_EXECUTE_EVENT       = WM_MESSAGE.WM_USER + 20,
    WFS_SERVICE_EVENT       = WM_MESSAGE.WM_USER + 21,
    WFS_USER_EVENT          = WM_MESSAGE.WM_USER + 22,
    WFS_SYSTEM_EVENT        = WM_MESSAGE.WM_USER + 23,

    WFS_TIMER_EVENT         = WM_MESSAGE.WM_USER + 100
}