call tsc.cmd --outDir ./js xfsalm.ts
call tsc.cmd --outDir ./js xfsbcr.ts
call tsc.cmd --outDir ./js xfscam.ts
call tsc.cmd --outDir ./js xfscdm.ts
call tsc.cmd --outDir ./js xfsceu.ts
call tsc.cmd --outDir ./js xfschk.ts
call tsc.cmd --outDir ./js xfscim.ts
call tsc.cmd --outDir ./js xfscrd.ts
call tsc.cmd --outDir ./js xfsdep.ts
call tsc.cmd --outDir ./js xfsidc.ts
call tsc.cmd --outDir ./js xfsipm.ts
call tsc.cmd --outDir ./js xfspin.ts
call tsc.cmd --outDir ./js xfsptr.ts
call tsc.cmd --outDir ./js xfssiu.ts
call tsc.cmd --outDir ./js xfsttu.ts
call tsc.cmd --outDir ./js xfsvdm.ts