/// <reference path="xfsapi.ts"/>
/**
 * DEP 命令
 * @namespace
*/
var DEP;
(function (DEP) {
    var WFS_SERVICE_CLASS_DEP = (6);
    var WFS_SERVICE_CLASS_VERSION_DEP = (0x1E03) /* Version 3.30 */;
    var WFS_SERVICE_CLASS_NAME_DEP = "DEP";
    var DEP_SERVICE_OFFSET = (WFS_SERVICE_CLASS_DEP * 100);
    /* DEP Info Commands */
    var INF;
    (function (INF) {
        INF[INF["WFS_INF_DEP_STATUS"] = (DEP_SERVICE_OFFSET + 1)] = "WFS_INF_DEP_STATUS";
        INF[INF["WFS_INF_DEP_CAPABILITIES"] = (DEP_SERVICE_OFFSET + 2)] = "WFS_INF_DEP_CAPABILITIES";
    })(INF = DEP.INF || (DEP.INF = {}));
    /* DEP Execute Commands */
    var CMD;
    (function (CMD) {
        CMD[CMD["WFS_CMD_DEP_ENTRY"] = (DEP_SERVICE_OFFSET + 1)] = "WFS_CMD_DEP_ENTRY";
        CMD[CMD["WFS_CMD_DEP_DISPENSE"] = (DEP_SERVICE_OFFSET + 2)] = "WFS_CMD_DEP_DISPENSE";
        CMD[CMD["WFS_CMD_DEP_RETRACT"] = (DEP_SERVICE_OFFSET + 3)] = "WFS_CMD_DEP_RETRACT";
        CMD[CMD["WFS_CMD_DEP_RESET_COUNT"] = (DEP_SERVICE_OFFSET + 5)] = "WFS_CMD_DEP_RESET_COUNT";
        CMD[CMD["WFS_CMD_DEP_RESET"] = (DEP_SERVICE_OFFSET + 6)] = "WFS_CMD_DEP_RESET";
        CMD[CMD["WFS_CMD_DEP_SET_GUIDANCE_LIGHT"] = (DEP_SERVICE_OFFSET + 7)] = "WFS_CMD_DEP_SET_GUIDANCE_LIGHT";
        CMD[CMD["WFS_CMD_DEP_SUPPLY_REPLENISH"] = (DEP_SERVICE_OFFSET + 8)] = "WFS_CMD_DEP_SUPPLY_REPLENISH";
        CMD[CMD["WFS_CMD_DEP_POWER_SAVE_CONTROL"] = (DEP_SERVICE_OFFSET + 9)] = "WFS_CMD_DEP_POWER_SAVE_CONTROL";
        CMD[CMD["WFS_CMD_DEP_SYNCHRONIZE_COMMAND"] = (DEP_SERVICE_OFFSET + 10)] = "WFS_CMD_DEP_SYNCHRONIZE_COMMAND";
    })(CMD = DEP.CMD || (DEP.CMD = {}));
    /* DEP Messages */
    var EVENT;
    (function (EVENT) {
        EVENT[EVENT["WFS_SRVE_DEP_ENVTAKEN"] = (DEP_SERVICE_OFFSET + 1)] = "WFS_SRVE_DEP_ENVTAKEN";
        EVENT[EVENT["WFS_EXEE_DEP_ENVDEPOSITED"] = (DEP_SERVICE_OFFSET + 2)] = "WFS_EXEE_DEP_ENVDEPOSITED";
        EVENT[EVENT["WFS_EXEE_DEP_DEPOSITERROR"] = (DEP_SERVICE_OFFSET + 3)] = "WFS_EXEE_DEP_DEPOSITERROR";
        EVENT[EVENT["WFS_USRE_DEP_DEPTHRESHOLD"] = (DEP_SERVICE_OFFSET + 4)] = "WFS_USRE_DEP_DEPTHRESHOLD";
        EVENT[EVENT["WFS_USRE_DEP_TONERTHRESHOLD"] = (DEP_SERVICE_OFFSET + 5)] = "WFS_USRE_DEP_TONERTHRESHOLD";
        EVENT[EVENT["WFS_USRE_DEP_ENVTHRESHOLD"] = (DEP_SERVICE_OFFSET + 6)] = "WFS_USRE_DEP_ENVTHRESHOLD";
        EVENT[EVENT["WFS_SRVE_DEP_CONTINSERTED"] = (DEP_SERVICE_OFFSET + 7)] = "WFS_SRVE_DEP_CONTINSERTED";
        EVENT[EVENT["WFS_SRVE_DEP_CONTREMOVED"] = (DEP_SERVICE_OFFSET + 8)] = "WFS_SRVE_DEP_CONTREMOVED";
        EVENT[EVENT["WFS_SRVE_DEP_ENVINSERTED"] = (DEP_SERVICE_OFFSET + 9)] = "WFS_SRVE_DEP_ENVINSERTED";
        EVENT[EVENT["WFS_SRVE_DEP_MEDIADETECTED"] = (DEP_SERVICE_OFFSET + 10)] = "WFS_SRVE_DEP_MEDIADETECTED";
        EVENT[EVENT["WFS_EXEE_DEP_INSERTDEPOSIT"] = (DEP_SERVICE_OFFSET + 11)] = "WFS_EXEE_DEP_INSERTDEPOSIT";
        EVENT[EVENT["WFS_SRVE_DEP_DEVICEPOSITION"] = (DEP_SERVICE_OFFSET + 12)] = "WFS_SRVE_DEP_DEVICEPOSITION";
        EVENT[EVENT["WFS_SRVE_DEP_POWER_SAVE_CHANGE"] = (DEP_SERVICE_OFFSET + 13)] = "WFS_SRVE_DEP_POWER_SAVE_CHANGE";
    })(EVENT = DEP.EVENT || (DEP.EVENT = {}));
})(DEP || (DEP = {}));
