/// <reference path="xfsapi.ts"/>
/**
 * IDC 命令
 * @namespace
*/
var IDC;
(function (IDC) {
    var WFS_SERVICE_CLASS_IDC = (2);
    var WFS_SERVICE_CLASS_NAME_IDC = "IDC";
    var WFS_SERVICE_CLASS_VERSION_IDC = (0x1E03); /* Version 3.30 */
    var IDC_SERVICE_OFFSET = (WFS_SERVICE_CLASS_IDC * 100);
    /* IDC Info Commands */
    var INF;
    (function (INF) {
        INF[INF["WFS_INF_IDC_STATUS"] = (IDC_SERVICE_OFFSET + 1)] = "WFS_INF_IDC_STATUS";
        INF[INF["WFS_INF_IDC_CAPABILITIES"] = (IDC_SERVICE_OFFSET + 2)] = "WFS_INF_IDC_CAPABILITIES";
        INF[INF["WFS_INF_IDC_FORM_LIST"] = (IDC_SERVICE_OFFSET + 3)] = "WFS_INF_IDC_FORM_LIST";
        INF[INF["WFS_INF_IDC_QUERY_FORM"] = (IDC_SERVICE_OFFSET + 4)] = "WFS_INF_IDC_QUERY_FORM";
        INF[INF["WFS_INF_IDC_QUERY_IFM_IDENTIFIER"] = (IDC_SERVICE_OFFSET + 5)] = "WFS_INF_IDC_QUERY_IFM_IDENTIFIER";
        INF[INF["WFS_INF_IDC_EMVCLESS_QUERY_APPLICATIONS"] = (IDC_SERVICE_OFFSET + 6)] = "WFS_INF_IDC_EMVCLESS_QUERY_APPLICATIONS";
    })(INF = IDC.INF || (IDC.INF = {}));
    /* IDC Execute Commands */
    var CMD;
    (function (CMD) {
        CMD[CMD["WFS_CMD_IDC_READ_TRACK"] = (IDC_SERVICE_OFFSET + 1)] = "WFS_CMD_IDC_READ_TRACK";
        CMD[CMD["WFS_CMD_IDC_WRITE_TRACK"] = (IDC_SERVICE_OFFSET + 2)] = "WFS_CMD_IDC_WRITE_TRACK";
        CMD[CMD["WFS_CMD_IDC_EJECT_CARD"] = (IDC_SERVICE_OFFSET + 3)] = "WFS_CMD_IDC_EJECT_CARD";
        CMD[CMD["WFS_CMD_IDC_RETAIN_CARD"] = (IDC_SERVICE_OFFSET + 4)] = "WFS_CMD_IDC_RETAIN_CARD";
        CMD[CMD["WFS_CMD_IDC_RESET_COUNT"] = (IDC_SERVICE_OFFSET + 5)] = "WFS_CMD_IDC_RESET_COUNT";
        CMD[CMD["WFS_CMD_IDC_SETKEY"] = (IDC_SERVICE_OFFSET + 6)] = "WFS_CMD_IDC_SETKEY";
        CMD[CMD["WFS_CMD_IDC_READ_RAW_DATA"] = (IDC_SERVICE_OFFSET + 7)] = "WFS_CMD_IDC_READ_RAW_DATA";
        CMD[CMD["WFS_CMD_IDC_WRITE_RAW_DATA"] = (IDC_SERVICE_OFFSET + 8)] = "WFS_CMD_IDC_WRITE_RAW_DATA";
        CMD[CMD["WFS_CMD_IDC_CHIP_IO"] = (IDC_SERVICE_OFFSET + 9)] = "WFS_CMD_IDC_CHIP_IO";
        CMD[CMD["WFS_CMD_IDC_RESET"] = (IDC_SERVICE_OFFSET + 10)] = "WFS_CMD_IDC_RESET";
        CMD[CMD["WFS_CMD_IDC_CHIP_POWER"] = (IDC_SERVICE_OFFSET + 11)] = "WFS_CMD_IDC_CHIP_POWER";
        CMD[CMD["WFS_CMD_IDC_PARSE_DATA"] = (IDC_SERVICE_OFFSET + 12)] = "WFS_CMD_IDC_PARSE_DATA";
        CMD[CMD["WFS_CMD_IDC_SET_GUIDANCE_LIGHT"] = (IDC_SERVICE_OFFSET + 13)] = "WFS_CMD_IDC_SET_GUIDANCE_LIGHT";
        CMD[CMD["WFS_CMD_IDC_POWER_SAVE_CONTROL"] = (IDC_SERVICE_OFFSET + 14)] = "WFS_CMD_IDC_POWER_SAVE_CONTROL";
        CMD[CMD["WFS_CMD_IDC_PARK_CARD"] = (IDC_SERVICE_OFFSET + 15)] = "WFS_CMD_IDC_PARK_CARD";
        CMD[CMD["WFS_CMD_IDC_EMVCLESS_CONFIGURE"] = (IDC_SERVICE_OFFSET + 16)] = "WFS_CMD_IDC_EMVCLESS_CONFIGURE";
        CMD[CMD["WFS_CMD_IDC_EMVCLESS_PERFORM_TRANSACTION"] = (IDC_SERVICE_OFFSET + 17)] = "WFS_CMD_IDC_EMVCLESS_PERFORM_TRANSACTION";
        CMD[CMD["WFS_CMD_IDC_EMVCLESS_ISSUERUPDATE"] = (IDC_SERVICE_OFFSET + 18)] = "WFS_CMD_IDC_EMVCLESS_ISSUERUPDATE";
        CMD[CMD["WFS_CMD_IDC_SYNCHRONIZE_COMMAND"] = (IDC_SERVICE_OFFSET + 19)] = "WFS_CMD_IDC_SYNCHRONIZE_COMMAND";
    })(CMD = IDC.CMD || (IDC.CMD = {}));
    /* IDC Messages */
    var EVENT;
    (function (EVENT) {
        EVENT[EVENT["WFS_EXEE_IDC_INVALIDTRACKDATA"] = (IDC_SERVICE_OFFSET + 1)] = "WFS_EXEE_IDC_INVALIDTRACKDATA";
        EVENT[EVENT["WFS_EXEE_IDC_MEDIAINSERTED"] = (IDC_SERVICE_OFFSET + 3)] = "WFS_EXEE_IDC_MEDIAINSERTED";
        EVENT[EVENT["WFS_SRVE_IDC_MEDIAREMOVED"] = (IDC_SERVICE_OFFSET + 4)] = "WFS_SRVE_IDC_MEDIAREMOVED";
        EVENT[EVENT["WFS_SRVE_IDC_CARDACTION"] = (IDC_SERVICE_OFFSET + 5)] = "WFS_SRVE_IDC_CARDACTION";
        EVENT[EVENT["WFS_USRE_IDC_RETAINBINTHRESHOLD"] = (IDC_SERVICE_OFFSET + 6)] = "WFS_USRE_IDC_RETAINBINTHRESHOLD";
        EVENT[EVENT["WFS_EXEE_IDC_INVALIDMEDIA"] = (IDC_SERVICE_OFFSET + 7)] = "WFS_EXEE_IDC_INVALIDMEDIA";
        EVENT[EVENT["WFS_EXEE_IDC_MEDIARETAINED"] = (IDC_SERVICE_OFFSET + 8)] = "WFS_EXEE_IDC_MEDIARETAINED";
        EVENT[EVENT["WFS_SRVE_IDC_MEDIADETECTED"] = (IDC_SERVICE_OFFSET + 9)] = "WFS_SRVE_IDC_MEDIADETECTED";
        EVENT[EVENT["WFS_SRVE_IDC_RETAINBININSERTED"] = (IDC_SERVICE_OFFSET + 10)] = "WFS_SRVE_IDC_RETAINBININSERTED";
        EVENT[EVENT["WFS_SRVE_IDC_RETAINBINREMOVED"] = (IDC_SERVICE_OFFSET + 11)] = "WFS_SRVE_IDC_RETAINBINREMOVED";
        EVENT[EVENT["WFS_EXEE_IDC_INSERTCARD"] = (IDC_SERVICE_OFFSET + 12)] = "WFS_EXEE_IDC_INSERTCARD";
        EVENT[EVENT["WFS_SRVE_IDC_DEVICEPOSITION"] = (IDC_SERVICE_OFFSET + 13)] = "WFS_SRVE_IDC_DEVICEPOSITION";
        EVENT[EVENT["WFS_SRVE_IDC_POWER_SAVE_CHANGE"] = (IDC_SERVICE_OFFSET + 14)] = "WFS_SRVE_IDC_POWER_SAVE_CHANGE";
        EVENT[EVENT["WFS_EXEE_IDC_TRACKDETECTED"] = (IDC_SERVICE_OFFSET + 15)] = "WFS_EXEE_IDC_TRACKDETECTED";
        EVENT[EVENT["WFS_EXEE_IDC_EMVCLESSREADSTATUS"] = (IDC_SERVICE_OFFSET + 16)] = "WFS_EXEE_IDC_EMVCLESSREADSTATUS";
    })(EVENT = IDC.EVENT || (IDC.EVENT = {}));
})(IDC || (IDC = {}));
