/// <reference path="xfsapi.ts"/>
/**
 * IPM 命令
 * @namespace
*/
var IPM;
(function (IPM) {
    var WFS_SERVICE_CLASS_IPM = (16);
    var WFS_SERVICE_CLASS_VERSION_IPM = (0x1E03) /* Version 3.30 */;
    var WFS_SERVICE_CLASS_NAME_IPM = "IPM";
    var IPM_SERVICE_OFFSET = (WFS_SERVICE_CLASS_IPM * 100);
    /* IPM Info Commands */
    var INF;
    (function (INF) {
        INF[INF["WFS_INF_IPM_STATUS"] = (IPM_SERVICE_OFFSET + 1)] = "WFS_INF_IPM_STATUS";
        INF[INF["WFS_INF_IPM_CAPABILITIES"] = (IPM_SERVICE_OFFSET + 2)] = "WFS_INF_IPM_CAPABILITIES";
        INF[INF["WFS_INF_IPM_CODELINE_MAPPING"] = (IPM_SERVICE_OFFSET + 3)] = "WFS_INF_IPM_CODELINE_MAPPING";
        INF[INF["WFS_INF_IPM_MEDIA_BIN_INFO"] = (IPM_SERVICE_OFFSET + 4)] = "WFS_INF_IPM_MEDIA_BIN_INFO";
        INF[INF["WFS_INF_IPM_TRANSACTION_STATUS"] = (IPM_SERVICE_OFFSET + 5)] = "WFS_INF_IPM_TRANSACTION_STATUS";
        INF[INF["WFS_INF_IPM_MEDIA_BIN_CAPABILITIES"] = (IPM_SERVICE_OFFSET + 6)] = "WFS_INF_IPM_MEDIA_BIN_CAPABILITIES";
    })(INF = IPM.INF || (IPM.INF = {}));
    /* IPM Execute Commands */
    var CMD;
    (function (CMD) {
        CMD[CMD["WFS_CMD_IPM_MEDIA_IN"] = (IPM_SERVICE_OFFSET + 1)] = "WFS_CMD_IPM_MEDIA_IN";
        CMD[CMD["WFS_CMD_IPM_MEDIA_IN_END"] = (IPM_SERVICE_OFFSET + 2)] = "WFS_CMD_IPM_MEDIA_IN_END";
        CMD[CMD["WFS_CMD_IPM_MEDIA_IN_ROLLBACK"] = (IPM_SERVICE_OFFSET + 3)] = "WFS_CMD_IPM_MEDIA_IN_ROLLBACK";
        CMD[CMD["WFS_CMD_IPM_READ_IMAGE"] = (IPM_SERVICE_OFFSET + 4)] = "WFS_CMD_IPM_READ_IMAGE";
        CMD[CMD["WFS_CMD_IPM_SET_DESTINATION"] = (IPM_SERVICE_OFFSET + 5)] = "WFS_CMD_IPM_SET_DESTINATION";
        CMD[CMD["WFS_CMD_IPM_PRESENT_MEDIA"] = (IPM_SERVICE_OFFSET + 6)] = "WFS_CMD_IPM_PRESENT_MEDIA";
        CMD[CMD["WFS_CMD_IPM_RETRACT_MEDIA"] = (IPM_SERVICE_OFFSET + 7)] = "WFS_CMD_IPM_RETRACT_MEDIA";
        CMD[CMD["WFS_CMD_IPM_PRINT_TEXT"] = (IPM_SERVICE_OFFSET + 8)] = "WFS_CMD_IPM_PRINT_TEXT";
        CMD[CMD["WFS_CMD_IPM_SET_MEDIA_BIN_INFO"] = (IPM_SERVICE_OFFSET + 9)] = "WFS_CMD_IPM_SET_MEDIA_BIN_INFO";
        CMD[CMD["WFS_CMD_IPM_RESET"] = (IPM_SERVICE_OFFSET + 10)] = "WFS_CMD_IPM_RESET";
        CMD[CMD["WFS_CMD_IPM_SET_GUIDANCE_LIGHT"] = (IPM_SERVICE_OFFSET + 11)] = "WFS_CMD_IPM_SET_GUIDANCE_LIGHT";
        CMD[CMD["WFS_CMD_IPM_GET_NEXT_ITEM"] = (IPM_SERVICE_OFFSET + 12)] = "WFS_CMD_IPM_GET_NEXT_ITEM";
        CMD[CMD["WFS_CMD_IPM_ACTION_ITEM"] = (IPM_SERVICE_OFFSET + 13)] = "WFS_CMD_IPM_ACTION_ITEM";
        CMD[CMD["WFS_CMD_IPM_EXPEL_MEDIA"] = (IPM_SERVICE_OFFSET + 14)] = "WFS_CMD_IPM_EXPEL_MEDIA";
        CMD[CMD["WFS_CMD_IPM_GET_IMAGE_AFTER_PRINT"] = (IPM_SERVICE_OFFSET + 15)] = "WFS_CMD_IPM_GET_IMAGE_AFTER_PRINT";
        CMD[CMD["WFS_CMD_IPM_ACCEPT_ITEM"] = (IPM_SERVICE_OFFSET + 16)] = "WFS_CMD_IPM_ACCEPT_ITEM";
        CMD[CMD["WFS_CMD_IPM_SUPPLY_REPLENISH"] = (IPM_SERVICE_OFFSET + 17)] = "WFS_CMD_IPM_SUPPLY_REPLENISH";
        CMD[CMD["WFS_CMD_IPM_POWER_SAVE_CONTROL"] = (IPM_SERVICE_OFFSET + 18)] = "WFS_CMD_IPM_POWER_SAVE_CONTROL";
        CMD[CMD["WFS_CMD_IPM_SET_MODE"] = (IPM_SERVICE_OFFSET + 19)] = "WFS_CMD_IPM_SET_MODE";
        CMD[CMD["WFS_CMD_IPM_SYNCHRONIZE_COMMAND"] = (IPM_SERVICE_OFFSET + 20)] = "WFS_CMD_IPM_SYNCHRONIZE_COMMAND";
    })(CMD = IPM.CMD || (IPM.CMD = {}));
    /* IPM Messages */
    var EVENT;
    (function (EVENT) {
        EVENT[EVENT["WFS_EXEE_IPM_NOMEDIA"] = (IPM_SERVICE_OFFSET + 1)] = "WFS_EXEE_IPM_NOMEDIA";
        EVENT[EVENT["WFS_EXEE_IPM_MEDIAINSERTED"] = (IPM_SERVICE_OFFSET + 2)] = "WFS_EXEE_IPM_MEDIAINSERTED";
        EVENT[EVENT["WFS_USRE_IPM_MEDIABINTHRESHOLD"] = (IPM_SERVICE_OFFSET + 3)] = "WFS_USRE_IPM_MEDIABINTHRESHOLD";
        EVENT[EVENT["WFS_SRVE_IPM_MEDIABININFOCHANGED"] = (IPM_SERVICE_OFFSET + 4)] = "WFS_SRVE_IPM_MEDIABININFOCHANGED";
        EVENT[EVENT["WFS_EXEE_IPM_MEDIABINERROR"] = (IPM_SERVICE_OFFSET + 5)] = "WFS_EXEE_IPM_MEDIABINERROR";
        EVENT[EVENT["WFS_SRVE_IPM_MEDIATAKEN"] = (IPM_SERVICE_OFFSET + 6)] = "WFS_SRVE_IPM_MEDIATAKEN";
        EVENT[EVENT["WFS_USRE_IPM_TONERTHRESHOLD"] = (IPM_SERVICE_OFFSET + 7)] = "WFS_USRE_IPM_TONERTHRESHOLD";
        EVENT[EVENT["WFS_USRE_IPM_SCANNERTHRESHOLD"] = (IPM_SERVICE_OFFSET + 8)] = "WFS_USRE_IPM_SCANNERTHRESHOLD";
        EVENT[EVENT["WFS_USRE_IPM_INKTHRESHOLD"] = (IPM_SERVICE_OFFSET + 9)] = "WFS_USRE_IPM_INKTHRESHOLD";
        EVENT[EVENT["WFS_SRVE_IPM_MEDIADETECTED"] = (IPM_SERVICE_OFFSET + 10)] = "WFS_SRVE_IPM_MEDIADETECTED";
        EVENT[EVENT["WFS_EXEE_IPM_MEDIAPRESENTED"] = (IPM_SERVICE_OFFSET + 11)] = "WFS_EXEE_IPM_MEDIAPRESENTED";
        EVENT[EVENT["WFS_EXEE_IPM_MEDIAREFUSED"] = (IPM_SERVICE_OFFSET + 12)] = "WFS_EXEE_IPM_MEDIAREFUSED";
        EVENT[EVENT["WFS_EXEE_IPM_MEDIADATA"] = (IPM_SERVICE_OFFSET + 13)] = "WFS_EXEE_IPM_MEDIADATA";
        EVENT[EVENT["WFS_USRE_IPM_MICRTHRESHOLD"] = (IPM_SERVICE_OFFSET + 14)] = "WFS_USRE_IPM_MICRTHRESHOLD";
        EVENT[EVENT["WFS_EXEE_IPM_MEDIAREJECTED"] = (IPM_SERVICE_OFFSET + 15)] = "WFS_EXEE_IPM_MEDIAREJECTED";
        EVENT[EVENT["WFS_SRVE_IPM_DEVICEPOSITION"] = (IPM_SERVICE_OFFSET + 16)] = "WFS_SRVE_IPM_DEVICEPOSITION";
        EVENT[EVENT["WFS_SRVE_IPM_POWER_SAVE_CHANGE"] = (IPM_SERVICE_OFFSET + 17)] = "WFS_SRVE_IPM_POWER_SAVE_CHANGE";
        EVENT[EVENT["WFS_SRVE_IPM_SHUTTERSTATUSCHANGED"] = (IPM_SERVICE_OFFSET + 18)] = "WFS_SRVE_IPM_SHUTTERSTATUSCHANGED";
    })(EVENT = IPM.EVENT || (IPM.EVENT = {}));
})(IPM || (IPM = {}));
