/// <reference path="xfsapi.ts"/>
/**
 * PTR 命令
 * @namespace
*/
var PTR;
(function (PTR) {
    var WFS_SERVICE_CLASS_PTR = (1);
    var WFS_SERVICE_CLASS_VERSION_PTR = (0x1E03) /* Version 3.30 */;
    var WFS_SERVICE_CLASS_NAME_PTR = "PTR";
    var PTR_SERVICE_OFFSET = (WFS_SERVICE_CLASS_PTR * 100);
    /* PTR Info Commands */
    var INF;
    (function (INF) {
        INF[INF["WFS_INF_PTR_STATUS"] = (PTR_SERVICE_OFFSET + 1)] = "WFS_INF_PTR_STATUS";
        INF[INF["WFS_INF_PTR_CAPABILITIES"] = (PTR_SERVICE_OFFSET + 2)] = "WFS_INF_PTR_CAPABILITIES";
        INF[INF["WFS_INF_PTR_FORM_LIST"] = (PTR_SERVICE_OFFSET + 3)] = "WFS_INF_PTR_FORM_LIST";
        INF[INF["WFS_INF_PTR_MEDIA_LIST"] = (PTR_SERVICE_OFFSET + 4)] = "WFS_INF_PTR_MEDIA_LIST";
        INF[INF["WFS_INF_PTR_QUERY_FORM"] = (PTR_SERVICE_OFFSET + 5)] = "WFS_INF_PTR_QUERY_FORM";
        INF[INF["WFS_INF_PTR_QUERY_MEDIA"] = (PTR_SERVICE_OFFSET + 6)] = "WFS_INF_PTR_QUERY_MEDIA";
        INF[INF["WFS_INF_PTR_QUERY_FIELD"] = (PTR_SERVICE_OFFSET + 7)] = "WFS_INF_PTR_QUERY_FIELD";
        INF[INF["WFS_INF_PTR_CODELINE_MAPPING"] = (PTR_SERVICE_OFFSET + 8)] = "WFS_INF_PTR_CODELINE_MAPPING";
    })(INF = PTR.INF || (PTR.INF = {}));
    /* PTR Execute Commands */
    var CMD;
    (function (CMD) {
        CMD[CMD["WFS_CMD_PTR_CONTROL_MEDIA"] = (PTR_SERVICE_OFFSET + 1)] = "WFS_CMD_PTR_CONTROL_MEDIA";
        CMD[CMD["WFS_CMD_PTR_PRINT_FORM"] = (PTR_SERVICE_OFFSET + 2)] = "WFS_CMD_PTR_PRINT_FORM";
        CMD[CMD["WFS_CMD_PTR_READ_FORM"] = (PTR_SERVICE_OFFSET + 3)] = "WFS_CMD_PTR_READ_FORM";
        CMD[CMD["WFS_CMD_PTR_RAW_DATA"] = (PTR_SERVICE_OFFSET + 4)] = "WFS_CMD_PTR_RAW_DATA";
        CMD[CMD["WFS_CMD_PTR_MEDIA_EXTENTS"] = (PTR_SERVICE_OFFSET + 5)] = "WFS_CMD_PTR_MEDIA_EXTENTS";
        CMD[CMD["WFS_CMD_PTR_RESET_COUNT"] = (PTR_SERVICE_OFFSET + 6)] = "WFS_CMD_PTR_RESET_COUNT";
        CMD[CMD["WFS_CMD_PTR_READ_IMAGE"] = (PTR_SERVICE_OFFSET + 7)] = "WFS_CMD_PTR_READ_IMAGE";
        CMD[CMD["WFS_CMD_PTR_RESET"] = (PTR_SERVICE_OFFSET + 8)] = "WFS_CMD_PTR_RESET";
        CMD[CMD["WFS_CMD_PTR_RETRACT_MEDIA"] = (PTR_SERVICE_OFFSET + 9)] = "WFS_CMD_PTR_RETRACT_MEDIA";
        CMD[CMD["WFS_CMD_PTR_DISPENSE_PAPER"] = (PTR_SERVICE_OFFSET + 10)] = "WFS_CMD_PTR_DISPENSE_PAPER";
        CMD[CMD["WFS_CMD_PTR_SET_GUIDANCE_LIGHT"] = (PTR_SERVICE_OFFSET + 11)] = "WFS_CMD_PTR_SET_GUIDANCE_LIGHT";
        CMD[CMD["WFS_CMD_PTR_PRINT_RAW_FILE"] = (PTR_SERVICE_OFFSET + 12)] = "WFS_CMD_PTR_PRINT_RAW_FILE";
        CMD[CMD["WFS_CMD_PTR_LOAD_DEFINITION"] = (PTR_SERVICE_OFFSET + 13)] = "WFS_CMD_PTR_LOAD_DEFINITION";
        CMD[CMD["WFS_CMD_PTR_SUPPLY_REPLENISH"] = (PTR_SERVICE_OFFSET + 14)] = "WFS_CMD_PTR_SUPPLY_REPLENISH";
        CMD[CMD["WFS_CMD_PTR_POWER_SAVE_CONTROL"] = (PTR_SERVICE_OFFSET + 15)] = "WFS_CMD_PTR_POWER_SAVE_CONTROL";
        CMD[CMD["WFS_CMD_PTR_CONTROL_PASSBOOK"] = (PTR_SERVICE_OFFSET + 16)] = "WFS_CMD_PTR_CONTROL_PASSBOOK";
        CMD[CMD["WFS_CMD_PTR_SET_BLACK_MARK_MODE"] = (PTR_SERVICE_OFFSET + 17)] = "WFS_CMD_PTR_SET_BLACK_MARK_MODE";
        CMD[CMD["WFS_CMD_PTR_SYNCHRONIZE_COMMAND"] = (PTR_SERVICE_OFFSET + 18)] = "WFS_CMD_PTR_SYNCHRONIZE_COMMAND";
    })(CMD = PTR.CMD || (PTR.CMD = {}));
    /* PTR Messages */
    var EVENT;
    (function (EVENT) {
        EVENT[EVENT["WFS_EXEE_PTR_NOMEDIA"] = (PTR_SERVICE_OFFSET + 1)] = "WFS_EXEE_PTR_NOMEDIA";
        EVENT[EVENT["WFS_EXEE_PTR_MEDIAINSERTED"] = (PTR_SERVICE_OFFSET + 2)] = "WFS_EXEE_PTR_MEDIAINSERTED";
        EVENT[EVENT["WFS_EXEE_PTR_FIELDERROR"] = (PTR_SERVICE_OFFSET + 3)] = "WFS_EXEE_PTR_FIELDERROR";
        EVENT[EVENT["WFS_EXEE_PTR_FIELDWARNING"] = (PTR_SERVICE_OFFSET + 4)] = "WFS_EXEE_PTR_FIELDWARNING";
        EVENT[EVENT["WFS_USRE_PTR_RETRACTBINTHRESHOLD"] = (PTR_SERVICE_OFFSET + 5)] = "WFS_USRE_PTR_RETRACTBINTHRESHOLD";
        EVENT[EVENT["WFS_SRVE_PTR_MEDIATAKEN"] = (PTR_SERVICE_OFFSET + 6)] = "WFS_SRVE_PTR_MEDIATAKEN";
        EVENT[EVENT["WFS_USRE_PTR_PAPERTHRESHOLD"] = (PTR_SERVICE_OFFSET + 7)] = "WFS_USRE_PTR_PAPERTHRESHOLD";
        EVENT[EVENT["WFS_USRE_PTR_TONERTHRESHOLD"] = (PTR_SERVICE_OFFSET + 8)] = "WFS_USRE_PTR_TONERTHRESHOLD";
        EVENT[EVENT["WFS_SRVE_PTR_MEDIAINSERTED"] = (PTR_SERVICE_OFFSET + 9)] = "WFS_SRVE_PTR_MEDIAINSERTED";
        EVENT[EVENT["WFS_USRE_PTR_LAMPTHRESHOLD"] = (PTR_SERVICE_OFFSET + 10)] = "WFS_USRE_PTR_LAMPTHRESHOLD";
        EVENT[EVENT["WFS_USRE_PTR_INKTHRESHOLD"] = (PTR_SERVICE_OFFSET + 11)] = "WFS_USRE_PTR_INKTHRESHOLD";
        EVENT[EVENT["WFS_SRVE_PTR_MEDIADETECTED"] = (PTR_SERVICE_OFFSET + 12)] = "WFS_SRVE_PTR_MEDIADETECTED";
        EVENT[EVENT["WFS_SRVE_PTR_RETRACTBINSTATUS"] = (PTR_SERVICE_OFFSET + 13)] = "WFS_SRVE_PTR_RETRACTBINSTATUS";
        EVENT[EVENT["WFS_EXEE_PTR_MEDIAPRESENTED"] = (PTR_SERVICE_OFFSET + 14)] = "WFS_EXEE_PTR_MEDIAPRESENTED";
        EVENT[EVENT["WFS_SRVE_PTR_DEFINITIONLOADED"] = (PTR_SERVICE_OFFSET + 15)] = "WFS_SRVE_PTR_DEFINITIONLOADED";
        EVENT[EVENT["WFS_EXEE_PTR_MEDIAREJECTED"] = (PTR_SERVICE_OFFSET + 16)] = "WFS_EXEE_PTR_MEDIAREJECTED";
        EVENT[EVENT["WFS_SRVE_PTR_MEDIAPRESENTED"] = (PTR_SERVICE_OFFSET + 17)] = "WFS_SRVE_PTR_MEDIAPRESENTED";
        EVENT[EVENT["WFS_SRVE_PTR_MEDIAAUTORETRACTED"] = (PTR_SERVICE_OFFSET + 18)] = "WFS_SRVE_PTR_MEDIAAUTORETRACTED";
        EVENT[EVENT["WFS_SRVE_PTR_DEVICEPOSITION"] = (PTR_SERVICE_OFFSET + 19)] = "WFS_SRVE_PTR_DEVICEPOSITION";
        EVENT[EVENT["WFS_SRVE_PTR_POWER_SAVE_CHANGE"] = (PTR_SERVICE_OFFSET + 20)] = "WFS_SRVE_PTR_POWER_SAVE_CHANGE";
    })(EVENT = PTR.EVENT || (PTR.EVENT = {}));
})(PTR || (PTR = {}));
