/// <reference path="xfsapi.ts"/>
/**
 * VDM 命令
 * @namespace
*/
var VDM;
(function (VDM) {
    var WFS_SERVICE_CLASS_VDM = (9);
    var WFS_SERVICE_CLASS_VERSION_VDM = (0x1E03) /* Version 3.30 */;
    var WFS_SERVICE_CLASS_NAME_VDM = "VDM";
    var VDM_SERVICE_OFFSET = (WFS_SERVICE_CLASS_VDM * 100);
    /* VDM Info Commands */
    var INF;
    (function (INF) {
        INF[INF["WFS_INF_VDM_STATUS"] = (VDM_SERVICE_OFFSET + 1)] = "WFS_INF_VDM_STATUS";
        INF[INF["WFS_INF_VDM_CAPABILITIES"] = (VDM_SERVICE_OFFSET + 2)] = "WFS_INF_VDM_CAPABILITIES";
        INF[INF["WFS_INF_VDM_ACTIVE_INTERFACE"] = (VDM_SERVICE_OFFSET + 3)] = "WFS_INF_VDM_ACTIVE_INTERFACE";
    })(INF = VDM.INF || (VDM.INF = {}));
    /* VDM Execute Commands */
    var CMD;
    (function (CMD) {
        CMD[CMD["WFS_CMD_VDM_ENTER_MODE_REQ"] = (VDM_SERVICE_OFFSET + 1)] = "WFS_CMD_VDM_ENTER_MODE_REQ";
        CMD[CMD["WFS_CMD_VDM_ENTER_MODE_ACK"] = (VDM_SERVICE_OFFSET + 2)] = "WFS_CMD_VDM_ENTER_MODE_ACK";
        CMD[CMD["WFS_CMD_VDM_EXIT_MODE_REQ"] = (VDM_SERVICE_OFFSET + 3)] = "WFS_CMD_VDM_EXIT_MODE_REQ";
        CMD[CMD["WFS_CMD_VDM_EXIT_MODE_ACK"] = (VDM_SERVICE_OFFSET + 4)] = "WFS_CMD_VDM_EXIT_MODE_ACK";
        CMD[CMD["WFS_CMD_VDM_SET_ACTIVE_INTERFACE"] = (VDM_SERVICE_OFFSET + 5)] = "WFS_CMD_VDM_SET_ACTIVE_INTERFACE";
    })(CMD = VDM.CMD || (VDM.CMD = {}));
    /* VDM Messages */
    var EVENT;
    (function (EVENT) {
        EVENT[EVENT["WFS_SRVE_VDM_ENTER_MODE_REQ"] = (VDM_SERVICE_OFFSET + 1)] = "WFS_SRVE_VDM_ENTER_MODE_REQ";
        EVENT[EVENT["WFS_SRVE_VDM_EXIT_MODE_REQ"] = (VDM_SERVICE_OFFSET + 2)] = "WFS_SRVE_VDM_EXIT_MODE_REQ";
        EVENT[EVENT["WFS_SYSE_VDM_MODEENTERED"] = (VDM_SERVICE_OFFSET + 3)] = "WFS_SYSE_VDM_MODEENTERED";
        EVENT[EVENT["WFS_SYSE_VDM_MODEEXITED"] = (VDM_SERVICE_OFFSET + 4)] = "WFS_SYSE_VDM_MODEEXITED";
        EVENT[EVENT["WFS_SRVE_VDM_INTERFACE_CHANGED"] = (VDM_SERVICE_OFFSET + 5)] = "WFS_SRVE_VDM_INTERFACE_CHANGED";
    })(EVENT = VDM.EVENT || (VDM.EVENT = {}));
})(VDM || (VDM = {}));
